services:
  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor # google registry
    container_name: cadvisor
    hostname: cadvisor
    privileged: true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/repos/home-docker/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-config:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    expose:
      - 8080
    networks:
      - monitoring

  node_exporter:
    restart: unless-stopped
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    hostname: node_exporter
    pid: host
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host
    expose:
      - 9100
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring