services:
  frontend:
    restart: unless-stopped
    image: ghcr.io/coldfirel15/gamecontainermanager:${DOCKER_TAG_FRONT:-main}
    container_name: gamecontainermanager-front
    hostname: gamecontainermanager-front
    environment:
      DOCKERCONTAINERMANAGER_AUTHENTICATION: "True"
      DOCKERCONTAINERMANAGER_BACKEND_URL: ${DOCKERCONTAINERMANAGER_BACKEND_URL}
      DOCKERCONTAINERMANAGER_BACKEND_MAC_ADDR: ${DOCKERCONTAINERMANAGER_BACKEND_MAC_ADDR}
      DOCKERCONTAINERMANAGER_DEBUG: "False"
      DOCKERCONTAINERMANAGER_DISCORD_CLIENT_ID: ${DOCKERCONTAINERMANAGER_DISCORD_CLIENT_ID}
      DOCKERCONTAINERMANAGER_DISCORD_CLIENT_SECRET: ${DOCKERCONTAINERMANAGER_DISCORD_CLIENT_SECRET}
      DOCKERCONTAINERMANAGER_FRONTEND_URL: ${DOCKERCONTAINERMANAGER_FRONTEND_URL}
      DOCKERCONTAINERMANAGER_SECRET_KEY: ${DOCKERCONTAINERMANAGER_SECRET_KEY}
      DOCKERCONTAINERMANAGER_SERVICE_TYPE: frontend
    expose:
      - 5000
    network_mode: "host"

  bot:
    restart: unless-stopped
    image: ghcr.io/coldfirel15/gamecontainermanager:${DOCKER_TAG_BOT:-main}
    container_name: gamecontainermanager-bot
    hostname: gamecontainermanager-bot
    environment:
      TZ: Europe/Paris
      DOCKERCONTAINERMANAGER_BACKEND_URL: ${DOCKERCONTAINERMANAGER_BACKEND_URL}
      DOCKERCONTAINERMANAGER_DEBUG: "False"
      DOCKERCONTAINERMANAGER_DISCORD_TOKEN: ${DISCORD_TOKEN}
      DOCKERCONTAINERMANAGER_FRONTEND_URL: ${DOCKERCONTAINERMANAGER_FRONTEND_URL}
      DOCKERCONTAINERMANAGER_SERVICE_TYPE: bot
    networks:
      - gamecontainermanager
    expose:
      - 5000
    healthcheck:
      disable: true

networks:
  gamecontainermanager:
    name: gamecontainermanager