services:
  heimdall:
    restart: unless-stopped
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/heimdall:/config
    networks:
    - web

networks:
  web:
    external: true