services:
  heimdall:
    restart: unless-stopped
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/heimdall:/config
    networks:
    - web

networks:
  web:
    external: true