version: '2.1'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /home/docker/heimdall:/config
    ports:
      - ${PERSONNAL_HEIMDALL_PORT}:443
    networks:
    - web

networks:
  web:
    external: true