version: '3.8'

services:
  heimdall:
    restart: unless-stopped
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /home/docker/heimdall:/config
    networks:
    - web

networks:
  web:
    external: true