services:
  duplicati:
    restart: unless-stopped
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.duplicati.tls: true
      traefik.http.routers.duplicati.tls.certresolver: production
      traefik.http.routers.duplicati.middlewares: authentik@docker
      traefik.http.routers.duplicati.entrypoints: web, websecure
      traefik.http.routers.duplicati.rule: Host(`duplicati.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.duplicati.service: duplicati
      traefik.http.services.duplicati.loadBalancer.server.port: 8200
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/duplicati:/config
      - /${RAID_DATA_DIRECTORY}/backups:/backups
      - /${RAID_DATA_DIRECTORY}/partage:/source
    expose:
      - 8200
    networks:
      - webinternal

networks:
  webinternal:
    name: webinternal