services:
  duplicati:
    restart: unless-stopped
    image: docker.io/duplicati/duplicati:${TAG_DUPLICATI}
    container_name: duplicati
    hostname: duplicati
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.duplicati.tls: true
      traefik.http.routers.duplicati.middlewares: authelia@docker
      traefik.http.routers.duplicati.entrypoints: websecure
      traefik.http.routers.duplicati.rule: Host(`duplicati.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.duplicati.service: duplicati
      traefik.http.services.duplicati.loadBalancer.server.port: 8200
    environment:
      TZ: Europe/Paris
      SETTINGS_ENCRYPTION_KEY: /run/secrets/SETTINGS_ENCRYPTION_KEY
      DUPLICATI__DISABLE_DB_ENCRYPTION: false
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: duplicati.${PERSONAL_DOMAINE_NAME}
      DUPLICATI__WEBSERVICE_PASSWORD: ${DUPLICATI_WEB_PWD}
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/duplicati:/data
      - /${RAID_DATA_DIRECTORY:?raid path is required}/backups:/backups
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker:/source/docker
      - /${RAID_DATA_DIRECTORY:?raid path is required}/partage:/source/partage
    expose:
      - 8200
    ports:
      - ${PERSONAL_DUPLICATI_PORT}:8200
    networks:
      - webinternal
    secrets:
      - SETTINGS_ENCRYPTION_KEY

secrets:
  SETTINGS_ENCRYPTION_KEY:
    file: /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-secret/duplicati/SETTINGS_ENCRYPTION_KEY.txt

networks:
  webinternal:
    name: webinternal