services:
  duplicati:
    restart: unless-stopped
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1002
      PGID: 100
      TZ: Europe/Paris
    volumes:
      - /home/docker/duplicati:/config
      - ${PATH_DATA}/backups:/backups
      - ${PATH_DATA}/partage:/source
    ports:
      - 8200:8200
    expose:
      - 8200
    networks:
      - duplicati

networks:
  duplicati:
    name: duplicati