version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.03.1
    restart: 'no'
    environment:
      TZ: Europe/Paris
      WEBPASSWORD: $PIHOLE_PASSWORD
      UID: $PERSONAL_UID_PIHOLE
      GID: $PERSONAL_GID_PIHOLE
      PIHOLE_UID: $PERSONAL_UID_PIHOLE
      DNSMASQ_USER: root
    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - var:/var
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.entrypoints: websecure
      traefik.http.routers.pihole.rule: Host(`pihole.$PERSONAL_DOMAINE_NAME`)
      traefik.http.services.pihole.loadbalancer.server.port: 80
    ports:
      - 53:53/tcp
      - 53:53/udp
      - $PERSONAL_PORT_PIHOLE:80
    networks:
      - web
    depends_on:
      - file-helper

  
  file-helper:
    container_name: file-helper-pihole
    restart: 'no'
    image: alpine:latest
    environment:
      - TZ=Europe/Paris
    command: 
        - sh
        - -c
        - >
          cd /var/log;
          ls;
          chown -R 777 lighttpd/;
    volumes:
      - var:/var
    networks:
      - web

volumes:
  var:
  data:
  dnsmasq:

networks:
  web:
    external: true