version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      WEBPASSWORD: $PI_HOLE_PASSWORD
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/etc/pihole/
      # - /volume1/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.entrypoints: websecure
      traefik.http.routers.pihole.rule: Host(`pihole.$PERSONAL_DOMAINE_NAME`)
      traefik.http.services.pihole.loadbalancer.server.port: 9000
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - web

volumes:
  data:

networks:
  web:
    external: true