version: '3'

services:
  pihole:
    container_name: pihole
    hostname: pi.hole
    image: pihole/pihole
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${PERSONNAL_LOCAL_IP}
      WEBUIBOXEDLAYOUT: traditional
      WEBTHEME: default-auto
      PIHOLE_DNS_: 127.0.0.1#53;1.1.1.1;1.0.0.1 #;2606:4700:4700:#1111;2606:4700:4700:#1001
      DNSSEC: true
      DHCP_ACTIVE: false
      DHCP_IPv6: false
      IPv6: false
      DNSMASQ_LISTENING : all
      TEMPERATUREUNIT: c
    volumes:
      - /home/docker/pi_hole/data:/etc/pihole
      - /home/docker/pi_hole/dnsmasq.d:/etc/dnsmasq.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8053:53/tcp
      - 8053:53/udp
      - ${PERSONAL_PORT_PIHOLE}:80
    networks:
    - web

networks:
  web:
    external: true