version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    WEBPASSWORD: $PI_HOLE_PASSWORD
    volumes:
      - data:/etc/pihole/
      # - /volume1/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    labels:
      traefik.enable=: true
      traefik.http.routers.pihole.rule: Host(`pihole.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.pihole.entrypoints: websecure
      traefik.http.routers.pihole.tls: true
      traefik.http.services.pihole.loadBalancer.server.port: 80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - web

volumes:
  data:

networks:
  web:
    external: true