---
source: docker
container_name:
 - authelia
labels:
  type: authelia
---
source: docker
container_name:
 - grafana
labels:
  type: grafana
---
source: docker
container_name:
 - immich-server
labels:
  type: immich
---
source: docker
container_name:
 - nextcloud-app
labels:
  type: Nextcloud
---
source: docker
container_name:
  - traefik
labels:
  type: traefik
---
source: docker
container_name:
 - vaultwarden
labels:
  type: Vaultwarden
---
