---
source: docker
container_name:
 - adguardhome
labels:
  type: adguardhome
---
source: docker
container_name:
 - authentik-server
labels:
  type: authentik
---
source: docker
container_name:
 - grafana
labels:
  type: grafana
---
filenames:
  - /var/log/nextcloud/nextcloud.log
labels:
  type: nextcloud
---
filenames:
  - /var/log/nextcloud/nginx/*.log
labels:
  type: nginx
---
filenames:
  - /var/log/openmediavault/*.*
labels:
  type: nextcloud
---
source: docker
container_name:
  - traefik
labels:
  type: traefik
---
source: docker
container_name:
 - vaultwarden
labels:
  type: Vaultwarden
---
