---
source: docker
container_name:
 - authelia
labels:
  type: authelia
---
source: docker
container_name:
 - grafana
labels:
  type: grafana
---
source: docker
container_name:
  - traefik
labels:
  type: traefik
---
source: docker
container_name:
 - vaultwarden
labels:
  type: Vaultwarden
---
source: docker
container_name:
 - immich_server
labels:
  type: immich
---
