services:
  proxy:
    image: traefik:2.10 #traefik:2.9.9
    restart: always
    container_name: traefik
    labels:
      diun.enable: true
      diun.watch_repos: true
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/traefik/certs:/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
      - ${PERSONAL_PORT_TRAEFIK}:8080
    command:
      - "--global.sendAnonymousUsage"
      - "--log.level=ERROR"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.file.directory=/certs/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    networks:
      - web
    depends_on: 
    - file-helper

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.${PERSONAL_DOMAINE_NAME}`)
    networks:
      - web
    ports:
      - ${PERSONAL_PORT_WHOAMI}:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on: 
    - proxy
  
  file-helper:
    container_name: file-helper-traefik
    restart: "no"
    image: alpine:latest
    environment:
      - TZ=Europe/Paris
    command: sh -c "wget https://raw.githubusercontent.com/Nicolas-mahe/Ansible-perso/Treafik/traefik/dynamic.yml -O /certs/dynamic.yml"
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/traefik/certs:/certs/
    networks:
      - web

networks:
  web:
    external: true