http:
  routers:
    box:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: box
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    dns:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: dns
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    nas:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: nas
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker   
    # mailcow:
    #   rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
    #   service: mailcow
      # tls: true
      # entrypoints:
      #   - websecure
    #   middlewares:
    #     - authentik@docker
    pve:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: pve
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    pve-1:
      rule: "Host(`domain-1.${PERSONAL_DOMAINE_NAME`)"
      service: pve-1
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    pve-2:
      rule: "Host(`domain-2.${PERSONAL_DOMAINE_NAME`)"
      service: pve-2
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    wifi:
      rule: "Host(`wifi.${PERSONAL_DOMAINE_NAME`)"
      service: wifi
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker

  services:
    box:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.254:${PERSONAL_BOX_PORT}"
    dns:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.2:${PERSONAL_DNS_PORT}"
    nas:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.2:${PERSONAL_NAS_PORT}"
    pve:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.3:${PERSONAL_PVE_PORT}" # pve-1
          - url: "http://${PERSONAL_NETWORK}.4:${PERSONAL_PVE_PORT}" # pve-2
        sticky:
          cookie:
            name: pve-host
            MaxAge: -1
            secure: true
        healthCheck:
          path: /
          port: ${PERSONAL_PVE_PORT}
          scheme: https
          interval: "10s"
          timeout: "3s"
    pve-1:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.3:${PERSONAL_PVE_PORT}"
    pve-2:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.4:${PERSONAL_PVE_PORT}"
    wifi:
      loadBalancer:
        servers:
          - url: "https://${PERSONAL_NETWORK}.253:443"

  #  minecraft:
  #     loadBalancer:
  #       servers:
  #         - url: "udp://${PERSONAL_NETWORK}.6:25565"

# udp:
#   routers:
#     minecraft:
#       rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
#       service: minecraft

