http:
  routers:
    box:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: box
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    dns:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: dns
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker
    nas:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: nas
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker   
    # mailcow:
    #   rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
    #   service: mailcow
      # tls: true
      # entrypoints:
      #   - websecure
    #   middlewares:
    #     - authentik@docker
    pve:
      rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
      service: pve
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - authentik@docker 

  services:
    box:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.254:{PERSONAL_BOX_PORT}"
    dns:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.2:{PERSONAL_DNS_PORT}"
    nas:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}:{PERSONAL_NAS_PORT}"
    pve:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}:{PERSONAL_PVE_PORT}"

  #  minecraft:
  #     loadBalancer:
  #       servers:
  #         - url: "udp://${PERSONAL_NETWORK}.6:25565"

# udp:
#   routers:
#     minecraft:
#       rule: "Host(`domain.${PERSONAL_DOMAINE_NAME}`)"
#       service: minecraft

