http:
  routers:
    satisfactory:
      entryPoints:
        - satisfactory-tcp
      rule: "Host(`satisfactory.${PERSONAL_DOMAIN_NAME}`)"
      service: satisfactory
      tls:
        certresolver: cloudflare

    box:
      rule: "Host(`box.${PERSONAL_DOMAIN_NAME}`)"
      service: box
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    dns:
      rule: "Host(`dns.${PERSONAL_DOMAIN_NAME}`)"
      service: dns
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    duplicati:
      rule: "Host(`duplicati.${PERSONAL_DOMAIN_NAME}`)"
      service: duplicati
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    homeassistant:
      rule: "Host(`homeassistant.${PERSONAL_DOMAIN_NAME}`)"
      service: homeassistant
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    nas:
      rule: "Host(`nas.${PERSONAL_DOMAIN_NAME}`)"
      service: nas
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    pfsense:
      rule: "Host(`pfsense.${PERSONAL_DOMAIN_NAME}`) || Host(`pdcvf1001pfsense.${PERSONAL_DOMAIN_NAME}`)"
      service: pfsense
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    smlight:
      rule: "Host(`pdcpx9003mr2u.${PERSONAL_DOMAIN_NAME}`)"
      service: smlight
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    zyxel-switch:
      rule: "Host(`zyxel-switch.${PERSONAL_DOMAIN_NAME}`)"
      service: zyxel-switch
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

    zyxel-wifi:
      rule: "Host(`zyxel-wifi.${PERSONAL_DOMAIN_NAME}`)"
      service: zyxel-wifi
      tls:
        certresolver: cloudflare
      entrypoints:
        - websecure
      middlewares:
        - authelia@docker
        - web-utils@docker

  services:
    satisfactory:
      loadBalancer:
        servers:
          - url: "https://${PERSONAL_NETWORK}.3:7777"
    box:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1:443"

    dns:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.2:81"

    duplicati:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.2:8201"

    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.9.2:8123"

    nas:
      loadBalancer:
        servers:
          - url: "https://${PERSONAL_NETWORK}.2:8443"

    pfsense:
      loadBalancer:
        servers:
          - url: "http://${PERSONAL_NETWORK}.1:80"

    smlight:
      loadBalancer:
        servers:
          - url: "http://192.168.9.3:80"

    zyxel-switch:
      loadBalancer:
        servers:
          - url: "https://${PERSONAL_NETWORK}.252:443"

    zyxel-wifi:
      loadBalancer:
        servers:
          - url: "https://${PERSONAL_NETWORK}.253:443"
tcp:
  routers:
    satisfactory:
      entryPoints:
        - satisfactory-tcp-reliable
      rule: "HostSNI(`*`)"
      service: satisfactory

    mail-smtp:
      rule: "HostSNI(`*`)"
      entryPoints:
        - mail-smtp
      service: mail-smtp

    mail-submissions:
      rule: "HostSNI(`*`)"
      entryPoints:
        - mail-submissions
      service: mail-submissions
      tls:
        passthrough: true

    mail-imaps:
      rule: "HostSNI(`*`)"
      entryPoints:
        - mail-imaps
      service: mail-imaps
      tls:
        passthrough: true

    mail-pop3s:
      rule: "HostSNI(`*`)"
      entryPoints:
        - mail-pop3s
      service: mail-pop3s
      tls:
        passthrough: true

  services:

    mail-smtp:
      loadBalancer:
        proxyProtocol:
          version: 1
        servers:
          - address: "mailserver:25"

    mail-submissions:
      loadBalancer:
        servers:
          - address: "mailserver:465"
        proxyProtocol:
          version: 1

    mail-imaps:
      loadBalancer:
        servers:
          - address: "mailserver:993"
        proxyProtocol:
          version: 2

    mail-pop3s:
      loadBalancer:
        servers:
          - address: "mailserver:995"
        proxyProtocol:
          version: 2
