services:
  grafana:
    restart: unless-stopped
    image: docker.io/grafana/grafana-oss:${GRAFANA_TAG:-latest}
    container_name: grafana
    hostname: grafana
    user: "${PERSONAL_GRAFANA_UID:-0}:${PERSONAL_GRAFANA_GID:-0}"
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.gafana.tls: true
      traefik.http.routers.gafana.middlewares: authelia@docker
      traefik.http.routers.gafana.entrypoints: websecure
      traefik.http.routers.gafana.rule: Host(`monitoring.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.gafana.service: gafana
      traefik.http.services.gafana.loadBalancer.server.port: 3000
    environment:
      TZ: Europe/Paris
      GF_SERVER_ROOT_URL: "https://monitoring.${PERSONAL_DOMAINE_NAME}"
      GF_AUTH_BASIC_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: "Authelia - ${PERSONAL_DOMAINE_NAME}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: preferred_username
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: name
      GF_AUTH_GENERIC_OAUTH_USE_PKCE: true
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.${PERSONAL_DOMAINE_NAME}/api/oidc/authorization"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.${PERSONAL_DOMAINE_NAME}/api/oidc/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.${PERSONAL_DOMAINE_NAME}/api/oidc/userinfo"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.${PERSONAL_DOMAINE_NAME}/logout"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'admin') && 'Admin' || contains(groups, 'Maison') && 'Editor' || 'Viewer'"
      # Optionally enable auto-login (bypasses Grafana login screen)
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: false
      GF_AUTH_GOOGLE_AUTO_LOGIN: false
      GF_AUTH_GITHUB_AUTO_LOGIN: false
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/grafana/data:/var/lib/grafana
    expose:
      - 3000
    networks:
      - webinternal
      - monitoring
    # healthcheck:
    #   test: ["CMD", "wget", "http://127.0.0.1:3000/api/health"]
    #   interval: 10s
    #   timeout: 15s
    #   retries: 10
    #   start_period: 40s 

  prometheus:
    restart: unless-stopped
    image: docker.io/prom/prometheus:${PROMETHEUS_TAG:-latest}
    container_name: prometheus
    hostname: prometheus
    user: "${PERSONAL_GRAFANA_UID:-0}:${PERSONAL_GRAFANA_GID:-0}"
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.prometheusdb.tls: true
      traefik.http.routers.prometheusdb.middlewares: authelia@docker
      traefik.http.routers.prometheusdb.entrypoints: websecure
      traefik.http.routers.prometheusdb.rule: Host(`prometheus.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.prometheusdb.service: prometheusdb
      traefik.http.services.prometheusdb.loadBalancer.server.port: 9090
    environment:
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/grafana/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    command: 
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PERSONAL_METRICS_RETENTION_TIME}"
    networks:
      - webinternal
      - monitoring
    # healthcheck:
    #   test: ["CMD", "wget", "http://127.0.0.1:9090"]
    #   interval: 10s
    #   timeout: 15s
    #   retries: 10
    #   start_period: 40s 

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_TAG:-latest} # google registry
    container_name: cadvisor
    hostname: cadvisor
    privileged: true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-config:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    expose:
      - 8080
    networks:
      - monitoring
    # healthcheck:
    #   test: ["CMD", "wget", "http://127.0.0.1:8080/healthz"]
    #   interval: 10s
    #   timeout: 15s
    #   retries: 10
    #   start_period: 40s 

  node_exporter:
    restart: unless-stopped
    image: quay.io/prometheus/node-exporter:${NODE_EXPORTER_TAG:-latest}
    container_name: node_exporter
    hostname: node_exporter
    pid: host
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host
    expose:
      - 9100
    networks:
      - monitoring

  # influxdb:
  #   restart: unless-stopped
  #   image: docker.io/library/influxdb:${INFLUXDB2_TAG:-2.7.10-alpine}
  #   container_name: influxdb2
  #   hostname: influxdb2
  #   labels:
  #     diun.enable: true
  #     diun.watch_repos: true
  #     traefik.enable: true
  #     traefik.http.routers.influxdb2.tls: true
  #     traefik.http.routers.influxdb2.middlewares: authelia@docker
  #     traefik.http.routers.influxdb2.entrypoints: websecure
  #     traefik.http.routers.influxdb2.rule: Host(`influxdb2.${PERSONAL_DOMAINE_NAME}`)
  #     traefik.http.routers.influxdb2.service: influxdb2
  #     traefik.http.services.influxdb2.loadbalancer.server.port: 8086
  #   environment:
  #     TZ: Europe/Paris
  #   # (Optional) change retention time
  #     DOCKER_INFLUXDB_INIT_RETENTION: ${PERSONAL_METRICS_RETENTION_TIME}  # (optional) configure data retention 1 week
  #   # (Optional) add admin token
  #     # DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${PERSONAL_INFLUXDB_ADMIN_TOKEN}  # (optional) set admin token
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/grafana/influxdb2/data:/var/lib/influxdb2
  #     - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/grafana/influxdb2/etc:/etc/influxdb2
  #   networks:
  #     - webinternal
  #     - monitoring

volumes:
  prometheus:
    name: prometheus

networks:
  monitoring:
    name: monitoring
  webinternal:
    name: webinternal
