services:
  app:
    restart: unless-stopped
    image: docker.io/nextcloud:${NEXTCLOUD_TAG:-latest}
    container_name: nextcloud-app
    hostname: nextcloud-app
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.middlewares: authelia@docker,nextcloud-headers@docker
      traefik.http.routers.nextcloud.rule: Host(`cloud.${PERSONAL_DOMAIN_NAME}`)
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadBalancer.server.port: 80
      # Middleware HSTS
      traefik.http.middlewares.nextcloud-headers.headers.customResponseHeaders.Strict-Transport-Security: 'max-age=15552000; includeSubDomains; preload'
    environment:
      MAIL_DOMAIN: ${PERSONAL_DOMAIN_NAME}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_API_TOKEN: ${NEXTCLOUD_API_TOKEN}
      NEXTCLOUD_EXTERNAL_GROUP: ${NEXTCLOUD_EXTERNAL_GROUP}
      NEXTCLOUD_INIT_HTACCES: true
      NEXTCLOUD_DEFAULT_QUOTA: ${NEXTCLOUD_DEFAULT_QUOTA}
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${PERSONAL_DOMAIN_NAME} nextcloud-app"
      NEXTCLOUD_SITE_NAME: ${NEXTCLOUD_SITE_NAME}
      NEXTCLOUD_SLOGAN: ${NEXTCLOUD_SLOGAN}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_PROVIDER_URL: https://auth.${PERSONAL_DOMAIN_NAME}
      OVERWRITEPROTOCOL: https
      PERSONAL_DOMAIN_NAME: ${PERSONAL_DOMAIN_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: nextcloud-postgres:5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      SMTP_AUTHTYPE: LOGIN
      SMTP_HOST: ${SMTP_HOST}
      SMTP_NAME: ${SMTP_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ssl
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/nextcloud:/var/www/html
      - /${RAID_DATA_DIRECTORY:?raid path is required}/nextcloud:/var/www/html/data
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/repos/home-docker/Nextcloud/hooks:/docker-entrypoint-hooks.d
      - /${RAID_DATA_DIRECTORY:?raid path is required}/partage:/mnt/partage
      - /${RAID_DATA_DIRECTORY:?raid path is required}/backups:/mnt/backups
    networks:
      - webinternal
      - nextcloud
    healthcheck:
      test: 'runuser -s /usr/local/bin/php - www-data /var/www/html/occ status 2>/dev/null | grep -e "installed: true" -e "maintenance: false" -e "needsDbUpgrade: false" | wc -l | [ "`cat`" = "3" ]'
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
  postgres:
    restart: unless-stopped
    image: docker.io/postgres:${POSTGRES_TAG:-17.6-bookworm}
    container_name: nextcloud-postgres
    hostname: nextcloud-postgres
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
    networks:
      - nextcloud
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  redis:
    restart: unless-stopped
    image: docker.io/library/redis:${REDIS_TAG:-alpine}
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - nextcloud-redis:/data
    networks:
      - nextcloud
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping | grep PONG"]
      start_period: 15s
      interval: 30s
      retries: 5
      timeout: 3s

volumes:
  nextcloud-postgres:
    name: nextcloud-postgres
  nextcloud-redis:
    name: nextcloud-redis

networks:
  nextcloud:
    name: nextcloud
    internal: true
  webinternal:
    name: webinternal