services:
  app:
    restart: unless-stopped
    image: docker.io/nextcloud:${NEXTCLOUD_TAG:-latest}
    container_name: nextcloud-app
    hostname: nextcloud-app
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.middlewares: authelia@docker,nextcloud-headers@docker
      traefik.http.routers.nextcloud.rule: Host(`cloud.${PERSONAL_DOMAIN_NAME}`)
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadBalancer.server.port: 80
      # Middleware HSTS
      traefik.http.middlewares.nextcloud-headers.headers.customResponseHeaders.Strict-Transport-Security: 'max-age=15552000; includeSubDomains; preload'
    environment:
      PERSONAL_DOMAIN_NAME: ${PERSONAL_DOMAIN_NAME}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${PERSONAL_DOMAIN_NAME}"
      NEXTCLOUD_INIT_HTACCES: true
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      POSTGRES_HOST: nextcloud-postgres:5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_SECURE: ssl
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: ${SMTP_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_DOMAIN: ${PERSONAL_DOMAIN_NAME}
      OIDC_PROVIDER_URL: https://auth.${PERSONAL_DOMAIN_NAME}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/nextcloud:/var/www/html
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/repos/home-docker/Nextcloud/hooks:/docker-entrypoint-hooks.d
      - /${RAID_DATA_DIRECTORY:?raid path is required}/partage:/mnt/partage
      - /${RAID_DATA_DIRECTORY:?raid path is required}/backups:/mnt/backups
    networks:
      - webinternal
      - nextcloud
  postgres:
    restart: unless-stopped
    image: docker.io/postgres:${POSTGRES_TAG:-17.6-bookworm}
    container_name: nextcloud-postgres
    hostname: nextcloud-postgres
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
    networks:
      - nextcloud

  redis:
    restart: unless-stopped
    image: docker.io/redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - nextcloud-redis:/data
    networks:
      - nextcloud

volumes:
  nextcloud-postgres:
    name: nextcloud-postgres
  nextcloud-redis:
    name: nextcloud-redis

networks:
  nextcloud:
    name: nextcloud
    internal: true
  webinternal:
    name: webinternal