services:
  nextcloud:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud
    hostname: nextcloud
    container_name: nextcloud
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.entrypoints: web, websecure
      traefik.http.routers.nextcloud.rule: Host(`cloud.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadBalancer.server.port: 80
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.${PERSONAL_DOMAINE_NAME}
      DOCKER_MODS: |
        lscr.io/linuxserver/mods:nextcloud-mediadc
        lscr.io/linuxserver/mods:nextcloud-memories
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/nextcloud/config:/config
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/nextcloud/data:/data
      - /${RAID_DATA_DIRECTORY}/partage/:/mnt/partage
      - /${RAID_DATA_DIRECTORY}/backups/:/mnt/backups
    depends_on:
      - mariadb
    ports:
      - ${PERSONAL_NEXTCLOUD_PORT?:port mandatory}:443
    expose:
      - 80
      - 443
    networks:
      - cloud-db
      - webinternal

  mariadb:
    restart: unless-stopped
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud_db
    hostname: nextcloud_db
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/nextcloud/mariadb:/config
    networks:
      - cloud-db
    command:
      "--log_bin_trust_function_creators=true"

networks:
  cloud-db:
    name: cloud-db
    internal: true
  webinternal:
    name: webinternal