services:
  nextcloud:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud
    hostname: nextcloud
    container_name: nextcloud
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: production
      traefik.http.routers.nextcloud.middlewares: authentik@docker
      traefik.http.routers.nextcloud.entrypoints: web, websecure
      traefik.http.routers.nextcloud.rule: Host(`cloud.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadBalancer.server.port: 80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.${PERSONAL_DOMAINE_NAME}
    volumes:
      - /home/docker/home-docker/timezone:/etc/timezone:ro
      - /home/docker/nextcloud/config:/config
      - /home/docker/nextcloud/data:/data
    depends_on:
      - mariadb
    # ports:
    #   - 450:443
    expose:
      - 80
      - 443
    networks:
      - cloud-db
      - webinternal

  mariadb:
    restart: unless-stopped
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud_db
    hostname: nextcloud_db
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
    volumes:
      - /home/docker/home-docker/timezone:/etc/timezone:ro
      - /home/docker/nextcloud/mariadb:/config
    networks:
      - cloud-db

networks:
  cloud-db:
    name: cloud-db
    internal: true
  webinternal:
    name: webinternal