version: '3.8'

services:
  nextcloud:
    restart: unless-stopped
    image: ghcr.io/linuxserver/nextcloud
    hostname: nextcloud
    container_name: nextcloud
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOST}
      DOCKER_MODS: ghcr.io/linuxserver/mods:nextcloud-mediadc|ghcr.io/linuxserver/mods:nextcloud-memories
    volumes:
      - /home/docker/nextcloud/config:/config
      - /home/docker/nextcloud/data:/data
    depends_on:
      - mariadb
    # ports:
    #   - 450:443
    networks:
      - cloud
      - cloud_db

  mariadb:
    restart: unless-stopped
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud_db
    hostname: nextcloud_db
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
    volumes:
      - /home/docker/nextcloud/mariadb:/config
    networks:
      - cloud_db

networks:
  cloud:
    name: cloud
  cloud_db:
    name: cloud_db