services:
  bdd:
    container_name: nextcloud_bdd
    image: mariadb
    networks:
      - web
    ports:
      - 3306:3306
    volumes:
      - bdd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PWD
      MYSQL_PASSWORD: $PWD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $USER
      TZ: Europe/Paris
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped

  app:
    container_name: nextcloud_app
    image: nextcloud
    volumes:
      - app:/var/www/html
      #- /srv/dev-disk-by-uuid-88861031-30c5-4c7f-9b3f-2f4087d6f927/Raid/Users/test:/mnt/data
    networks:
      - web
    ports:
      - 9080:80
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: $HOST
      MYSQL_PASSWORD: $PWD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $USER
      MYSQL_HOST: bdd
      config_is_read_only: false
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
    restart: unless-stopped
    links:
      - bdd
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`$HOST`)
      - traefik.http.routers.nextcloud.entrypoints=web
    
volumes:
  bdd:
  app:

networks:
  web:
    external: true