services:
  nextcloud:
    restart: unless-stopped
    image: ghcr.io/linuxserver/nextcloud
    hostname: nextcloud
    container_name: nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOST}
    volumes:
      - /home/docker/nextcloud/config:/config
      - nextcloud_data:/data
    depends_on:
      - mariadb
    ports:
      - 450:443
    networks:
      - web

  mariadb:
    restart: unless-stopped
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud_db
    hostname: nextcloud_db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
    volumes:
      - /home/docker/nextcloud/mariadb:/config
    networks:
      - web

volumes:
  nextcloud_data:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.1,rw,nolock,nfsvers=4"
      device: ":/export/nextcloud/data"

networks:
  web:
    external: true