services:
  nextcloud:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud
    hostname: nextcloud
    container_name: nextcloud
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOST}
    volumes:
      - /home/docker/nextcloud/config:/config
      - /home/docker/nextcloud/data:/data
      - nfs-films:/mnt/nfs-films
    depends_on:
      - mariadb
    ports:
      - 450:443
    networks:
      - cloud
      - cloud-db

  mariadb:
    restart: unless-stopped
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud_db
    hostname: nextcloud_db
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
    volumes:
      - /home/docker/nextcloud/mariadb:/config
    networks:
      - cloud-db

volumes:
  nfs-films:
    name:
      nextcloud-nfs-films
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=omv-vm,rw,nfsvers=3"
      device: ":/export/films"

networks:
  cloud:
    name: cloud
  cloud-db:
    name: cloud-db