services:
  cloudflare-ddns:
    restart: always
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      API_KEY: ${DNS_API_KEY}
      ZONE: ${PERSONAL_DOMAINE_NAME}
      PROXIED: true
      TZ: Europe/Paris
      DELETE_ON_STOP: true
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
    networks:
      - cloudflare-ddns

networks:
  cloudflare-ddns:
    name: cloudflare-ddns