services:
  cloudflare-ddns:
    restart: always
    container_name: Cloudflare-DNS
    image: oznu/cloudflare-ddns
    environment:
      - API_KEY=$DNS_API_KEY
      - ZONE=laura-et-nicolas.com
      - PROXIED=true
      - TZ= Europe/Paris
    labels:
      traefik.enable: true
      traefik.http.routers.cloudflare.tls: true
      traefik.http.routers.cloudflare.entrypoints: websecure
      traefik.http.routers.cloudflare.rule: Host(`cloudflare.$PERSONAL_DOMAINE_NAME`)
      traefik.http.routers.cloudflare.tls.certresolver: traefik_certs
      traefik.http.services.cloudflare.loadbalancer.server.port: $PERSONNAL_PORT
    networks:
      - web
    ports:
      - $PERSONNAL_PORT:80
networks:
  web:
    external: true