version: '2'

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns
    restart: always
    environment:
      API_KEY: ${DNS_API_KEY}
      ZONE: ${PERSONAL_DOMAINE_NAME}
      PROXIED: true
      TZ: Europe/Paris
      DELETE_ON_STOP: true
    networks:
      - web

networks:
  web:
    external: true