version: '3.8'

services:
  homepage:
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    hostname: homepage
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /home/docker/homepage/config:/app/config
      - /home/docker/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external: true