services:
  homepage:
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    hostname: homepage
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /home/docker/homepage/config:/app/config
      - /home/docker/homepage/images:/app/public/images
      - /home/docker/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/home-docker/timezone:/etc/timezone:ro
    networks:
      - homepage
      - crowdsec

networks:
  crowdsec:
    name: crowdsec
  homepage:
    name: homepage