version: '3.8'

services:
  homepage:
    restart: unless-stopped
    image: gethomepage/homepage
    container_name: homepage
    hostname: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /home/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external: true