services:
  diun:
    restart: unless-stopped
    image: docker.io/crazymax/diun
    container_name: diun
    hostname: diun.${PERSONAL_HOST}
    command: serve
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
      PUID: 1000
      GUID: 1000
      LOG_LEVEL: info
      LOG_JSON: false
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 17 * * *
      DIUN_PROVIDERS_DOCKER: true
      DIUN_NOTIF_DISCORD_WEBHOOKURL: ${DIUN_NOTIF_DISCORD_WEBHOOKURL}
      DIUN_NOTIF_DISCORD_RENDERFIELDS: true
      DIUN_NOTIF_DISCORD_TIMEOUT: 10s
      DIUN_NOTIF_DISCORD_TEMPLATEBODY: |
        Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/diun:/data
    networks:
      - diun

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    hostname: cadvisor
    privileged: true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - ${PERSONAL_CADVISOR_PORT}:8080
    networks:
      - diun

networks:
  diun:
    name: diun