services:
  diun:
    restart: unless-stopped
    image: docker.io/crazymax/diun:${DIUN_TAG:-latest}
    container_name: diun
    hostname: diun.${PERSONAL_HOST:?hostname is required}
    command: serve
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      TZ: Europe/Paris
      LOG_LEVEL: info
      LOG_JSON: false
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 17,22 * * *
      DIUN_PROVIDERS_DOCKER: true
      DIUN_NOTIF_DISCORD_WEBHOOKURL: ${DIUN_NOTIF_DISCORD_WEBHOOKURL:?webhook is required}
      DIUN_NOTIF_DISCORD_RENDERFIELDS: true
      DIUN_NOTIF_DISCORD_TIMEOUT: 10s
      DIUN_NOTIF_DISCORD_TEMPLATEBODY: |
        Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - diun:/data
    networks:
      - webinternal

volumes:
  diun:
    name: diun

networks:
  webinternal:
    name: webinternal