services:
  immich-server:
    restart: unless-stopped
    container_name: immich_server
    hostname: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      diun.enable: true
      diun.watch_repos: true
      traefik.enable: true
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.middlewares: authelia@docker
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.rule: Host(`photos.${PERSONAL_DOMAIN_NAME}`)
      traefik.http.routers.immich.service: immich
      traefik.http.services.immich.loadbalancer.server.port: 2283
    env_file:
      - stack.env
    environment:
      IMMICH_CONFIG_FILE: /immich-config.json
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/immich/library:/data
      - /${RAID_DATA_DIRECTORY:?raid path is required}/partage:/partage
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/immich/config.json:/immich-config.json:ro
    depends_on:
      - redis
      - database
    networks:
      - immich
      - webinternal

  immich-machine-learning:
    restart: unless-stopped
    container_name: immich_machine_learning
    hostname: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    labels:
      diun.enable: true
      diun.watch_repos: true
    env_file:
      - stack.env
    volumes:
      - model-cache:/cache
    networks:
      - immich

  redis:
    restart: unless-stopped
    container_name: immich_redis
    image:  docker.io/valkey/valkey:8-bookworm
    labels:
      diun.enable: true
      diun.watch_repos: true
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich

  database:
    restart: unless-stopped
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    shm_size: 128mb
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/immich/postgres:/var/lib/postgresql/data
    networks:
      - immich

volumes:
  model-cache:

networks:
  immich:
    name: immich
  webinternal:
    name: webinternal