services:
  adguardhome:
    restart: always
    image: docker.io/adguard/adguardhome:${ADGUARDHOME_TAG:-latest}
    container_name: adguardhome
    hostname: adguardhome
    environment:
      PUID: ${PUID}
      GUID: ${PGID}
      ADGUARDHOME_INTERFACE: ${ADGUARDHOME_INTERFACE:-eth0}
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/adguard/data:/opt/adguardhome/work
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/adguard/conf:/opt/adguardhome/conf
    network_mode: "host"
    healthcheck:
      test: nslookup www.google.com || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 2
