version: '3.3'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguard
    restart: always
    volumes:
      - /home/docker/adguard/data:/opt/adguardhome/work
      - /home/docker/adguard/config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - web

networks:
  web:
    external: true