services:
  librespeed:
    restart: unless-stopped
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    hostname: librespeed
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      PASSWORD: ${PERSONAL_LIBRESPEED_PWD}
    volumes:
      - /home/docker/librespeed:/config
    networks:
    - web

networks:
  web:
    external: true