version: "2.1"
services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=${PERSONAL_LIBRESPEED_PWD}
    volumes:
      - /home/docker/librespeed:/config
    ports:
      - ${PERSONAL_LIBRESPEED_PORT}:80
    restart: unless-stopped
    network_mode: bridge