services:
  librespeed:
    restart: unless-stopped
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    hostname: librespeed
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      PASSWORD: ${PERSONAL_LIBRESPEED_PWD}
    volumes:
      - /home/docker/librespeed:/config
    expose:
      - 80
    networks:
    - librespeed

networks:
  librespeed:
    name: librespeed