services:
  swag:
    restart: always
    image: lscr.io/linuxserver/swag
    container_name: swag
    hostname: swag
    labels:
      diun.enable: true
      diun.watch_repos: true
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      URL: ${PERSONAL_DOMAINE_NAME}
      VALIDATION: dns
      PROPAGATION: 30
      SUBDOMAINS: wildcard
      DNSPLUGIN: cloudflare
      EMAIL: ${PERSONAL_EMAIL}
      DOCKER_MODS_DEBUG: ${DOCKER_MODS_DEBUG}
      CROWDSEC_API_KEY: ${CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      CROWDSEC_F2B_DISABLE: false
      CROWDSEC_CAPTCHA_PROVIDER: recaptcha
      CROWDSEC_SITE_KEY: ${CROWDSEC_SITE_KEY}
      CROWDSEC_SECRET_KEY: ${CROWDSEC_SECRET_KEY}
      CROWDSEC_VERSION: ${CROWDSEC_VERSION}
      DISC_HOOK: ${DISC_HOOK}
      DISC_API: ${DISC_API}
      DISC_ME: ${DISC_ME}
      DOCKER_MODS: |
        lscr.io/linuxserver/mods:swag-auto-reload
        lscr.io/linuxserver/mods:swag-cloudflare-real-ip
        lscr.io/linuxserver/mods:swag-crowdsec${PERSONAL_CROWDSEC_VERSION}
        lscr.io/linuxserver/mods:swag-dashboard
        lscr.io/linuxserver/mods:swag-dbip
        lscr.io/linuxserver/mods:swag-f2bdiscord
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/swag:/config #Config Swag
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/authelia/config/authelia.log:/authelia/authelia.log:ro #Logs Authelia
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/nextcloud/config/nextcloud.log:/nextcloud/nextcloud.log:ro #Logs Nextcloud
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/vaultwarden/vaultwarden.log:/vaultwarden/vaultwarden.log:ro #Logs Vaultwarden
    ports:
      - 443:443
    expose:
      - 81
    networks:
      - swag
      - webinternal

  crowdsec:
    restart: always
    image: ghcr.io/crowdsecurity/crowdsec
    container_name: crowdsec
    hostname: crowdsec
    security_opt:
      - no-new-privileges=true
    labels:
      diun.enable: true
      diun.watch_repos: true
    depends_on:
      - authelia
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_SWAG: ${CROWDSEC_API_KEY}
      COLLECTIONS: crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/nginx crowdsecurity/nextcloud LePresidente/authelia Dominic-Wagner/vaultwarden
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/crowdsec/config:/etc/crowdsec #Config Crowdsec
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/crowdsec/data:/var/lib/crowdsec/data/ #Config Crowdsec
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/swag/log/nginx:/var/log/nginx:ro #Logs Swag
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/authelia/config/authelia.log:/var/log/authelia.log:ro #Logs Authelia
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/nextcloud/config/nextcloud.log:/var/log/nextcloud.log:ro #Logs Nextcloud
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/vaultwarden/vaultwarden.log:/var/log/vaultwarden.log:ro #Logs Vaultwarden
    expose:
      - 8080
    networks:
      - swag

  authelia:
    restart: always
    image: ghcr.io/authelia/authelia
    container_name: authelia
    hostname: authelia
    security_opt:
      - no-new-privileges=true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/authelia/config:/config
    expose:
      - 9091
    networks:
      - swag

networks:
  swag:
    name: swag
  webinternal:
    name: webinternal