services:
  swag:
    restart: always
    image: lscr.io/linuxserver/swag
    container_name: swag
    hostname: swag
    labels:
      diun.enable: true
      diun.watch_repos: true
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      URL: ${PERSONAL_DOMAINE_NAME}
      VALIDATION: dns
      PROPAGATION: 30
      SUBDOMAINS: wildcard
      DNSPLUGIN: cloudflare
      EMAIL: ${PERSONAL_EMAIL}
      DOCKER_MODS_DEBUG: ${DOCKER_MODS_DEBUG}
      CROWDSEC_API_KEY: ${CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      CROWDSEC_F2B_DISABLE: false
      CROWDSEC_CAPTCHA_PROVIDER: recaptcha
      CROWDSEC_SITE_KEY: ${CROWDSEC_SITE_KEY}
      CROWDSEC_SECRET_KEY: ${CROWDSEC_SECRET_KEY}
      CROWDSEC_VERSION: ${CROWDSEC_VERSION}
      DISC_HOOK: ${DISC_HOOK}
      DISC_API: ${DISC_API}
      DISC_ME: ${DISC_ME}
      DOCKER_MODS: |
        lscr.io/linuxserver/mods:swag-auto-reload
        lscr.io/linuxserver/mods:swag-cloudflare-real-ip
        lscr.io/linuxserver/mods:swag-crowdsec
        lscr.io/linuxserver/mods:swag-dashboard
        lscr.io/linuxserver/mods:swag-dbip
        lscr.io/linuxserver/mods:swag-f2bdiscord
    volumes:
      - /home/docker/swag:/config #Config Swag
      - /home/docker/authelia/config/authelia.log:/authelia/authelia.log:ro #Logs Authelia
      - /home/docker/nextcloud/config/nextcloud.log:/nextcloud/nextcloud.log:ro #Logs Nextcloud
      - /home/docker/vaultwarden/vaultwarden.log:/vaultwarden/vaultwarden.log:ro #Logs Vaultwarden
    ports:
      - 172.18.0.2:443:443
    networks:
      - authelia
      - cloud
      - crowdsec
      - duplicati
      - homepage
      - librespeed
      - local
      - portainer
      - vaultwarden
      - web

  crowdsec:
    restart: always
    image: ghcr.io/crowdsecurity/crowdsec
    container_name: crowdsec
    hostname: crowdsec
    security_opt:
      - no-new-privileges=true
    labels:
      diun.enable: true
      diun.watch_repos: true
    depends_on:
      - authelia
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_SWAG: ${CROWDSEC_API_KEY}
      COLLECTIONS: crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/nginx crowdsecurity/nextcloud LePresidente/authelia Dominic-Wagner/vaultwarden
    volumes:
      - /home/docker/crowdsec/config:/etc/crowdsec #Config Crowdsec
      - /home/docker/crowdsec/data:/var/lib/crowdsec/data/ #Config Crowdsec
      - /home/docker/swag/log/nginx:/var/log/nginx:ro #Logs Swag
      - /home/docker/authelia/config/authelia.log:/var/log/authelia.log:ro #Logs Authelia
      - /home/docker/nextcloud/config/nextcloud.log:/var/log/nextcloud.log:ro #Logs Nextcloud
      - /home/docker/vaultwarden/vaultwarden.log:/var/log/vaultwarden.log:ro #Logs Vaultwarden
    networks:
      - crowdsec

  authelia:
    restart: always
    image: ghcr.io/authelia/authelia
    container_name: authelia
    hostname: authelia
    security_opt:
      - no-new-privileges=true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /home/docker/authelia/config:/config
    expose:
      - 9091
    networks:
      - authelia

networks:
  authelia:
    name: authelia
  cloud:
    name: cloud
  crowdsec:
    name: crowdsec
  duplicati:
    name: duplicati
  homepage:
    name: homepage
  librespeed:
    name: librespeed
  local:
    name: local
  portainer:
    name: portainer
  vaultwarden:
    name: vaultwarden
  web:
    external: true