version: '2.1'

services:
  swag:
    restart: always
    image: ghcr.io/linuxserver/swag
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      URL: ${PERSONAL_DOMAINE_NAME}
      VALIDATION: dns
      PROPAGATION: 30
      SUBDOMAINS: wildcard
      DNSPLUGIN: cloudflare
      EMAIL: ${PERSONAL_EMAIL}
      DOCKER_MODS: linuxserver/mods:swag-dashboard #|lineserver/mods:swag-dbip
    volumes:
      - /home/docker/swag:/config #config Swag
      - /home/docker/authelia/config/authelia.log:/authelia/authelia.log:ro #Logs Authelia
      - /home/docker/nextcloud/config/nextcloud.log:/nextcloud/nextcloud.log:ro #Logs Nextcloud
    ports:
      - 443:443
    networks:
      - web

  authelia:
    restart: always
    image: authelia/authelia
    container_name: authelia
    hostname: authelia
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /home/docker/authelia/config:/config
      - /home/docker/authelia/log:/var/log
    expose:
      - 9091
    networks:
      - authelia-back
      - web

  mariadb:
    restart: unless-stopped
    image: ghcr.io/linuxserver/mariadb
    container_name: authelia_db
    hostname: authelia_db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_USER}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/docker/authelia/mariadb:/config
    networks:
      - authelia-back

networks:
  authelia-back:
    name: authelia-back

  web:
    external: true