---
#
# Access Control Configuration
#
# Access control is a list of rules defining the authorizations applied for one resource to users or group of users.
#
# If 'access_control' is not defined, ACL rules are disabled and the 'deny' rule is applied, i.e., access is denied
# to everyone. Otherwise restrictions follow the rules defined.
#
# Note: One can use the wildcard * to match any subdomain.
# It must stand at the beginning of the pattern. (example: *.${PERSONAL_DOMAINE_NAME})
#
# Note: You must put patterns containing wildcards between simple quotes for the YAML to be syntactically correct.
#
# Definition: A 'rule' is an object with the following keys: 'domain', 'subject', 'policy' and 'resources'.
#
# - 'domain' defines which domain or set of domains the rule applies to.
#
# - 'subject' defines the subject to apply authorizations to. This parameter is optional and matching any user if not
#    provided. If provided, the parameter represents either a user or a group. It should be of the form
#    'user:<username>' or 'group:<groupname>'.
#
# - 'policy' is the policy to apply to resources. It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
#
# - 'resources' is a list of regular expressions that matches a set of resources to apply the policy to. This parameter
#   is optional and matches any resource if not provided.
#
# Note: the order of the rules is important. The first policy matching (domain, resource, subject) applies.
access_control:
  # Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  # resource if there is no policy to be applied to the user.
  default_policy: 'two_factor'

  rules:
  ##################INTERNAL#############
    ## BYPASS
    - domain:
      - '${PERSONAL_DOMAINE_NAME}'
      - 'auth.${PERSONAL_DOMAINE_NAME}'
      - 'brainstorm.${PERSONAL_DOMAINE_NAME}'
      - 'brule-un-cierge.${PERSONAL_DOMAINE_NAME}'
      - 'bruleuncierge.${PERSONAL_DOMAINE_NAME}'
      - 'candle.${PERSONAL_DOMAINE_NAME}'
      - 'cloud.${PERSONAL_DOMAINE_NAME}'
      - 'dauphin-47400.${PERSONAL_DOMAINE_NAME}'
      - 'games-manager.${PERSONAL_DOMAINE_NAME}'
      - 'gitlab.${PERSONAL_DOMAINE_NAME}'
      - 'librespeed.${PERSONAL_DOMAINE_NAME}'
      - 'luna.${PERSONAL_DOMAINE_NAME}'
      - 'moi-unique-aux-monde.${PERSONAL_DOMAINE_NAME}'
      - 'play.${PERSONAL_DOMAINE_NAME}'
      - 'registry.${PERSONAL_DOMAINE_NAME}'
      - 'utils.${PERSONAL_DOMAINE_NAME}'
      - 'voiture.${PERSONAL_DOMAINE_NAME}'
      - 'www.${PERSONAL_DOMAINE_NAME}'
      policy: 'bypass'
      networks:
        - 'internal'

    ## RESTRICTED ACCES
    - domain_regex:
      - '^(pve).*\.chou-dou\.com$'
      - '^(pdc).*\.chou-dou\.com$'
      - '^(zyxel).*\.chou-dou\.com$'
      policy: 'one_factor'
      subject:
        - 'group:admin'
      networks:
        - 'internal'

    - domain:
      - 'box.${PERSONAL_DOMAINE_NAME}'
      - 'dns.${PERSONAL_DOMAINE_NAME}'
      - 'duplicati.${PERSONAL_DOMAINE_NAME}'
      - 'influxdb2.${PERSONAL_DOMAINE_NAME}'
      - 'management.${PERSONAL_DOMAINE_NAME}'
      - 'monitoring.${PERSONAL_DOMAINE_NAME}'
      - 'nas.${PERSONAL_DOMAINE_NAME}'
      - 'traefik.${PERSONAL_DOMAINE_NAME}'
      - 'prometheus.${PERSONAL_DOMAINE_NAME}'
      - 'python-test.${PERSONAL_DOMAINE_NAME}'
      - 'whoami.${PERSONAL_DOMAINE_NAME}'
      policy: 'one_factor'
      subject:
        - 'group:admin'
      networks:
        - 'internal'

    ## ADMIN PATH
    - domain:
      - 'pronostic.${PERSONAL_DOMAINE_NAME}'
      resources:
        - '^/liste([/?].*)?$'
        - '^/add_result([/?].*)?$'
      policy: 'two_factor'
      subject:
        - 'group:admin'
        - 'group:Maison'
      networks:
        - 'internal'

    - domain:
      - 'photos.${PERSONAL_DOMAINE_NAME}'
      - 'vaultwarden.${PERSONAL_DOMAINE_NAME}'
      resources:
        - '^/admin([/?].*)?$'
      policy: 'two_factor'
      subject:
        - 'group:admin'
      networks:
        - 'internal'

    ## BYPASS WITHOUT ADMIN PATH
    - domain:
      - 'photos.${PERSONAL_DOMAINE_NAME}'
      - 'pronostic.${PERSONAL_DOMAINE_NAME}'
      - 'vaultwarden.${PERSONAL_DOMAINE_NAME}'
      policy: 'bypass'
      networks:
        - 'internal'

    ## ADMIN
    - domain:
      - '${PERSONAL_DOMAINE_NAME}'
      - '*.${PERSONAL_DOMAINE_NAME}'
      policy: 'one_factor'
      subject:
        - 'group:admin'
      networks:
        - 'internal'


  ##################EXTERNAL#############
    ## BYPASS
    - domain:
      - '${PERSONAL_DOMAINE_NAME}'
      - 'auth.${PERSONAL_DOMAINE_NAME}'
      - 'brainstorm.${PERSONAL_DOMAINE_NAME}'
      - 'brule-un-cierge.${PERSONAL_DOMAINE_NAME}'
      - 'bruleuncierge.${PERSONAL_DOMAINE_NAME}'
      - 'candle.${PERSONAL_DOMAINE_NAME}'
      - 'cloud.${PERSONAL_DOMAINE_NAME}'
      - 'games-manager.${PERSONAL_DOMAINE_NAME}'
      - 'gitlab.${PERSONAL_DOMAINE_NAME}'
      - 'luna.${PERSONAL_DOMAINE_NAME}'
      - 'play.${PERSONAL_DOMAINE_NAME}'
      - 'registry.${PERSONAL_DOMAINE_NAME}'
      - 'utils.${PERSONAL_DOMAINE_NAME}'
      - 'voiture.${PERSONAL_DOMAINE_NAME}'
      policy: 'bypass'

    ## TWO_FACTOR
    - domain_regex:
      - '^(pve).*\.chou-dou\.com$'
      - '^(pdc).*\.chou-dou\.com$'
      - '^(zyxel).*\.chou-dou\.com$'
      policy: 'two_factor'
      subject:
        - 'group:admin'

    - domain:
      - 'box.${PERSONAL_DOMAINE_NAME}'
      - 'dns.${PERSONAL_DOMAINE_NAME}'
      - 'duplicati.${PERSONAL_DOMAINE_NAME}'
      - 'influxdb2.${PERSONAL_DOMAINE_NAME}'
      - 'nas.${PERSONAL_DOMAINE_NAME}'
      - 'traefik.${PERSONAL_DOMAINE_NAME}'
      - 'prometheus.${PERSONAL_DOMAINE_NAME}'
      - 'python-test.${PERSONAL_DOMAINE_NAME}'
      - 'whoami.${PERSONAL_DOMAINE_NAME}'
      policy: 'two_factor'
      subject:
        - 'group:admin'

    - domain:
      - 'management.${PERSONAL_DOMAINE_NAME}'
      - 'monitoring.${PERSONAL_DOMAINE_NAME}'
      policy: 'two_factor'
      subject:
        - 'group:admin'
        - 'group:Gamers'

    ## ONE_FACTOR
    - domain:
      - 'dauphin-47400.${PERSONAL_DOMAINE_NAME}'
      - 'librespeed.${PERSONAL_DOMAINE_NAME}'
      - 'moi-unique-aux-monde.${PERSONAL_DOMAINE_NAME}'
      - 'www.${PERSONAL_DOMAINE_NAME}'
      policy: 'one_factor'

    ## ADMIN PATH
    - domain:
      - 'pronostic.${PERSONAL_DOMAINE_NAME}'
      resources:
        - '^/liste([/?].*)?$'
        - '^/add_result([/?].*)?$'
      policy: 'two_factor'
      subject:
        - 'group:admin'
        - 'group:Maison'

    - domain:
      - 'photos.${PERSONAL_DOMAINE_NAME}'
      - 'vaultwarden.${PERSONAL_DOMAINE_NAME}'
      resources:
        - '^/admin([/?].*)?$'
      policy: 'two_factor'
      subject:
        - 'group:admin'
    
    ## BYPASS WITHOUT ADMIN PATH
    - domain:
      - 'photos.${PERSONAL_DOMAINE_NAME}'
      - 'pronostic.${PERSONAL_DOMAINE_NAME}'
      - 'vaultwarden.${PERSONAL_DOMAINE_NAME}'
      policy: 'bypass'

    ## ADMIN
    - domain:
      - '${PERSONAL_DOMAINE_NAME}'
      - '*.${PERSONAL_DOMAINE_NAME}'
      policy: 'two_factor'
      subject:
        - 'group:admin'
