---
#
# Access Control Configuration
#
# Access control is a list of rules defining the authorizations applied for one resource to users or group of users.
#
# If 'access_control' is not defined, ACL rules are disabled and the 'deny' rule is applied, i.e., access is denied
# to everyone. Otherwise restrictions follow the rules defined.
#
# Note: One can use the wildcard * to match any subdomain.
# It must stand at the beginning of the pattern. (example: *.${PERSONAL_DOMAINE_NAME})
#
# Note: You must put patterns containing wildcards between simple quotes for the YAML to be syntactically correct.
#
# Definition: A 'rule' is an object with the following keys: 'domain', 'subject', 'policy' and 'resources'.
#
# - 'domain' defines which domain or set of domains the rule applies to.
#
# - 'subject' defines the subject to apply authorizations to. This parameter is optional and matching any user if not
#    provided. If provided, the parameter represents either a user or a group. It should be of the form
#    'user:<username>' or 'group:<groupname>'.
#
# - 'policy' is the policy to apply to resources. It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
#
# - 'resources' is a list of regular expressions that matches a set of resources to apply the policy to. This parameter
#   is optional and matches any resource if not provided.
#
# Note: the order of the rules is important. The first policy matching (domain, resource, subject) applies.
access_control:
  # Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  # resource if there is no policy to be applied to the user.
  default_policy: 'deny'

