version: "2.1"

services:
  swag:
    image: linuxserver/swag
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=chou-dou.com
      - VALIDATION=dns
      - PROPAGATION= 30
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - EMAIL= ${PERSONAL_EMAIL}
    volumes:
      - /home/docker/reverse-proxy/swag:/config
    ports:
      - 443:443
    restart: always
    networks:
      - web

  authelia:
    image: authelia/authelia
    container_name: authelia
    hostname: authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/docker/reverse-proxy/authelia/config:/config
      - /home/docker/reverse-proxy/authelia/log:/var/log
    expose:
      - 9091
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true