version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.17.1
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`portainer.$PERSONAL_DOMAINE_NAME`)
      traefik.http.routers.whoami.tls.certresolver: traefik_certs
    ports:
      - 37834:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

volumes:
  data:

networks:
  web:
    external : true