version: '3.8'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.18.2
    restart: always
    environment:
      TZ: Europe/Paris
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`management.$PERSONAL_DOMAINE_NAME`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    ports:
      - $PERSONAL_PORT_PORTAINER:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    env_file:
      - .env

volumes:
  data:

networks:
  web:
    external: true