services:
  portainer:
    restart: always
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:${PERSONAL_PORTAINER_VERSION}
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    ports:
      - ${PERSONAL_PORT_PORTAINER}:9000
    volumes:
      - /home/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/home-docker/timezone:/etc/timezone:ro
    networks:
    - portainer

networks:
  portainer:
    name: portainer