version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.17.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.laura-et-nicolas.com`)"
      - "traefik.http.routers.portainer.entrypoints=web_secure"
    ports:
      - 37834:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

volumes:
  data:

networks:
  web:
    external : true