version: "3"

services:
  portainer:
    image: portainer/portainer-ee:2.17.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minecraft.rule=Host(`portainer.laura-et-nicolas.com`)"
      - "traefik.http.routers.minecraft.entrypoints=websecure"
      - "traefik.http.routers.minecraft.tls=true"
      - "traefik.http.routers.minecraft.tls.certresolver=cloudflare"
    restart: unless-stopped
    container_name: portainer
    ports:
      - 37834:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

volumes:
  data: {}

networks:
  web:
    external : true