services:
  minecraft:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: itzg/minecraft-server:java21
    container_name: minecraft-atm
    hostname: minecraft-atm
    tty: true
    stdin_open: true
    labels:
      diun.enable: true
      diun.watch_repos: true
      gamecontainermanager.enable: true
      gamecontainermanager.group: "Minecraft"
      gamecontainermanager.customlabel0: "atm.${PERSONAL_DOMAINE_NAME}"
    environment:
      TZ: Europe/Paris
      ALLOW_FLIGHT: "true"
      BROADCAST_CONSOLE_TO_OPS: TRUE
      BROADCAST_RCON_TO_OPS: TRUE
      CF_SLUG: all-the-mons
      CF_API_KEY: ${CF_API_KEY}
      CREATE_CONSOLE_IN_PIPE: TRUE
      ENABLE_AUTOPAUSE: FALSE
      ENFORCE_WHITELIST: TRUE
      EULA: TRUE
      ENABLE_STATUS: TRUE
      ENABLE_QUERY: TRUE
      ICON: https://media.forgecdn.net/avatars/thumbnails/1567/555/64/64/639016249214580144.png
      MAX_PLAYERS: 6
      MAX_TICK_TIME : -1
      MOD_PLATFORM: AUTO_CURSEFORGE
      MEMORY: "15G" #20G
      MOTD: "§b§l§oRaBByT Season 6:§r§l§o§2 All The Mons\n§6§kCest rigolo cette ligne qui bouge tout le temps"
      PAUSE_WHEN_EMPTY_SECONDS: -1
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 1
        kill @e[type=item]
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/minecraft/s6/prod:/data
    ports:
      - 25566:25565
    networks:
      - games

  # backups:
  #   restart: ${RESTART_POLICY:-unless-stopped}
  #   image: docker.io/itzg/mc-backup
  #   container_name: minecraft-atm-backups
  #   hostname: minecraft-atm-backups
  #   labels:
  #     diun.enable: true
  #     diun.watch_repos: true
  #   environment:
  #     PGID: 1000
  #     PUID: 1000
  #     TZ: Europe/Paris
  #     INITIAL_DELAY: 0
  #     BACKUP_INTERVAL: ${PERSONAL_INTERVAL_SAVE}
  #     BACKUP_NAME: RaBByT-S6
  #     PRUNE_BACKUPS_DAYS: 7
  #     PRUNE_RESTIC_RETENTION: --keep-within 7d
  #     RCON_HOST: minecraft-atm
  #     RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
  #     RCON_PASSWORD: ${PERSONAL_RCON_PWD}
  #     PAUSE_IF_NO_PLAYERS: TRUE
  #     DEST_DIR: /backups/Minecraft/s6
  #     SRC_DIR: /data
  #     LINK_LATEST: FALSE
  #     BACKUP_METHOD: tar
  #     TAR_COMPRESS_METHOD: gzip
  #     ZSTD_PARAMETERS: -3 --long=25 --single-thread
  #   volumes:
  #     - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/minecraft/s6/prod:/data
  #     - nfs_backups:/backups
  #   depends_on:
  #     minecraft:
  #       condition: service_healthy
  #   networks:
  #     - games

volumes:
  nfs_backups: ## Le nom de mon volume en montage NFS
    driver: local
    name: mc_atm_nfs_backups
    driver_opts:
      type: nfs
      o: addr=${PERSONAL_NETWORK}.2,nolock,soft,rw
      device: ":/export/backups"
networks:
  games:
    name: games