#https://github.com/itzg/docker-minecraft-server
#https://github.com/itzg/docker-mc-backup
#https://www.youtube.com/watch?v=PHJE60COs5g&ab_channel=OuiHeberg DNS

services:
  server:
    restart: unless-stopped
    image: docker.io/itzg/minecraft-server:java17-jdk
    container_name: minecraft-server
    hostname: minecraft-server
    tty: true
    stdin_open: true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PGID: 1000
      PUID: 100
      TZ: Europe/Paris
      ALLOW_FLIGHT: TRUE
      BROADCAST_CONSOLE_TO_OPS: TRUE
      BROADCAST_RCON_TO_OPS: TRUE
      CF_API_KEY: ${CF_API_KEY}
      CF_BASE_DIR: "/data"
      CF_FILE_ID: 5353015 #Ragnamod-VII-7.1.7
      CF_SLUG: ragnamod-vii
      DIFFICULTY: normal
      EULA: TRUE
      ENABLE_STATUS: TRUE
      ENABLE_QUERY: TRUE
      ENABLE_RCON: TRUE
      ENABLE_WHITELIST: TRUE
      FORCE_GAMEMODE: TRUE
      FORGE_VERSION: "47.2.32"
      ICON: /icon.jpg
      MAX_BUILD_HEIGHT: 320 # only under 320
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000000
      MEMORY: "16G"
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator
      MOTD: "§b§l§oRaBByT Season 5\n§f§kRagnamod-VII-7.1.7"
      ONLINE_MODE: TRUE
      OVERRIDE_ICON: TRUE
      PVP: TRUE
      QUERY_PORT: 25565
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 1
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
      SERVER_NAME: RaBByT_S5
      SIMULATION_DISTANCE: 7
      SNOOPER_ENABLED: FALSE
      SPAWN_PROTECTION: 0
      STOP_DURATION: 180
      TYPE: AUTO_CURSEFORGE
      VERSION: "1.18.2"
      VIEW_DISTANCE: 10
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/mc-s5/:/data
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/RaBByT.jpg:/icon.jpg:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/banned-ips.json:/data/banned-ips.json
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/banned-players.json:/data/banned-players.json
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/ops.json:/data/ops.json
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/whitelist.json:/data/whitelist.json
    ports:
      - ${PERSONAL_PORT_MINECRAFT}:25565
    networks:
      - minecraft

  ### Public VPN ###
  playit: #https://playit.gg
    restart: no
    image: ghcr.io/playit-cloud/playit-agent:0.15
    container_name: minecraft-playit
    hostname: minecraft-playit
    environment:
      SECRET_KEY: ${PLAYIT_SECRET_KEY}
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
    networks:
      - minecraft


networks:
  minecraft:
    name: minecraft