version: '3.8'
#https://github.com/itzg/docker-minecraft-server
#https://github.com/itzg/docker-mc-backup
#https://www.youtube.com/watch?v=PHJE60COs5g&ab_channel=OuiHeberg DNS

services:
  server:
    restart: unless-stopped
    container_name: minecraft-server
    image: itzg/minecraft-server:java17-jdk
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      ALLOW_FLIGHT: TRUE
      CF_API_KEY: ${CF_API_KEY}
      CF_BASE_DIR: "/data"
      CF_FILES_ID: 5048888
      CF_SLUG: ragnamod-vii
      DIFFICULTY: normal
      EULA: TRUE
      ENABLE_RCON: TRUE
      ENABLE_WHITELIST: TRUE
      FORCE_GAMEMODE: TRUE
      FORGE_VERSION: "40.2.9"
      ICON: /RaBByT-S4.jpg
      MAX_BUILD_HEIGHT: 320 # only under 320
      MAX_PLAYERS: 10
      MAX_WORLD_SIZE: 10000000
      MEMORY: "29G"
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator
      MOTD: "§b§l§oRaBByT Season V4 \n§f§kMinecraft docker Server"
      OPS: "RaBByt_Tv,TBMPQF"
      OVERRIDE_ICON: TRUE
      PERSONAL_PORT_MINECRAFT_RCON: ${PERSONAL_PORT_MINECRAFT_RCON}
      PERSONAL_RCON_PWD: ${PERSONAL_RCON_PWD}
      PGID: 1000
      PUID: 1000
      PVP: TRUE
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 1
        kill @e[type=item]
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
      SERVER_NAME: RaBByT_S4
      SIMULATION_DISTANCE: 6
      SNOOPER_ENABLED: FALSE
      SPAWN_PROTECTION: 0
      STOP_DURATION: 180
      TYPE: AUTO_CURSEFORGE
      TZ: Europe/Paris
      VERSION: "1.18.2"
      VIEW_DISTANCE: 10
    volumes:
      - /home/docker/mc-s4/data:/data
      - /home/docker/mc-s4/RaBByT-S4.jpg:/RaBByT-S4.jpg
      - /home/docker/mc-s4/whitelist.json:/data/whitelist.json
    ports:
      - ${PERSONAL_PORT_MINECRAFT}:25565
    network_mode: bridge
    tty: true
    stdin_open: true
    
  save:
    restart: unless-stopped
    image: itzg/mc-backup
    container_name: minecraft-save
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      INITIAL_DELAY: $PERSONAL_INTERVAL_SAVE
      BACKUP_INTERVAL: $PERSONAL_INTERVAL_SAVE
      SRC_DIR: /data
      BACKUP_NAME: world
      BACKUP_METHOD: tar
      PRUNE_BACKUPS_DAYS: 1
      PRUNE_RESTIC_RETENTION: --keep-within 1
      RCON_HOST: server
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      DEST_DIR: /backups
      LINK_LATEST: FALSE
      TAR_COMPRESS_METHOD: gzip
      ZSTD_PARAMETERS: -3 --long=50
      RCON_RETRIES: 10
      RCON_RETRY_INTERVAL: 10s
      EXCLUDES: "*.jar,cache,logs"
      PAUSE_IF_NO_PLAYERS: true
      PLAYERS_ONLINE_CHECK_INTERVAL: 1h
      PRE_BACKUP_SCRIPT: echo "Backup in progress"
      POST_BACKUP_SCRIPT: echo "Backup done"
    volumes:
      - /home/docker/mc-s4/data:/data:ro
      - /home/docker/mc-s4/backups:/backups
    network_mode: service:server