services:
  mc:
    restart: unless-stopped
    image: itzg/minecraft-server:java17-jdk
    container_name: minecraft
    hostname: minecraft
    tty: true
    stdin_open: true
    environment:
      TZ: Europe/Paris
      ALLOW_FLIGHT: "true"
      EULA: TRUE
      ENFORCE_WHITELIST: TRUE
      DEBUG: "false"
      FORGEVERSION: "40.2.21"
      TYPE: FORGE
      VERSION: "1.18.2"
      MEMORY: "6G"
      MOTD: "§b§l§oRaBByT Season 5:§r§l§o§2 Ragnamod-VII-7.1.7\n§6§kC'est rigolo cette lingne qui bouge tout le temps"
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/minecraft/temp:/data
    ports:
      - 25566:25565
    networks:
      - games

  ### Public VPN ###
  # playit: #https://playit.gg
  #   restart: no
  #   image: ghcr.io/playit-cloud/playit-agent:0.15
  #   container_name: minecraft-tunnel
  #   hostname: minecraft-tunnel
  #   labels:
  #     diun.enable: true
  #     diun.watch_repos: true
  #   environment:
  #     SECRET_KEY: ${PLAYIT_SECRET_KEY}
  #     TZ: Europe/Paris
  #   volumes:
  #     - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
  #   networks:
  #     - games

networks:
  games:
    name: games