version: "3.8"
#https://github.com/itzg/docker-minecraft-server
#https://github.com/itzg/docker-mc-backup

services:
  server:
    image: itzg/minecraft-server:2023.3.0
    labels:
      traefik.enable: true
      traefik.http.routers.minecraft.tls: true
      traefik.http.routers.minecraft.entrypoints: websecure
      traefik.http.routers.minecraft.rule: Host(`minecraft.$PERSONAL_DOMAINE_NAME`)
      traefik.http.services.minecraft.loadbalancer.server.port: $PERSONAL_PORT_MINECRAFT
    environment:
      UID: $PERSONAL_UID_MINECRAFT
      GID: $PERSONAL_GID_MINECRAFT
      EULA: TRUE
      MOTD: "RaBByT Season v3"
      VERSION: 1.18.2
      TYPE: FORGE
      FORGE_VERSION: 40.2.2
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=80"
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 10
      MAX_BUILD_HEIGHT: 320 # only under 320
      ENABLE_WHITELIST: TRUE
      DIFFICULTY: normal
      OPS: "RaBByt_Tv,TBMPQF"
      ALLOW_NETHER: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      GENERATE_STRUCTURES: TRUE
      SNOOPER_ENABLED: FALSE
      TZ: Europe/Paris
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator // not sure it work
      FORCE_GAMEMODE: TRUE # force default gamemode at connection
      HARDCORE: FALSE
      ALLOW_FLIGHT: TRUE
      MAX_WORLD_SIZE: 10000000
      SPAWN_ANIMALS: TRUE
      SPAWN_MONSTERS: TRUE
      SPAWN_NPCS: TRUE
      PVP: TRUE
      LEVEL_TYPE: normal # type of generating world
      SERVER_NAME: RaBByT_S3
      ENABLE_RCON: TRUE
      RCON_PASSWORD: $PERSONAL_RCON_PWD
      RCON_PORT: $PERSONAL_PORT_MINECRAFT_RCON
      RCON_CMDS_STARTUP:  |-
        gamerule playersSleepingPercentage 1
    deploy:
      resources:
        limits:
          memory: 24G
          cpus: '7'
    volumes:
      - data:/data
      - mods:/mods
    restart: unless-stopped
    ports:
      - $PERSONAL_PORT_MINECRAFT:25565
    networks:
      - web
    
  backups:
    image: itzg/mc-backup
    environment:
      TZ: Europe/Paris
      INITIAL_DELAY: 5m
      BACKUP_INTERVAL: 2h
      SRC_DIR: /data
      BACKUP_NAME: world
      BACKUP_METHOD: tar
      PRUNE_BACKUPS_DAYS: 7
      PRUNE_RESTIC_RETENTION: --keep-within 7d
      RCON_HOST: server
      RCON_PORT: $PERSONAL_PORT_MINECRAFT_RCON
      RCON_PASSWORD: $PERSONAL_RCON_PWD
      DEST_DIR: /backups
      LINK_LATEST: FALSE
      TAR_COMPRESS_METHOD: gzip
      ZSTD_PARAMETERS: -3 --long=50 --single-thread
      RCON_RETRIES: 10
      RCON_RETRY_INTERVAL: 10s
      # EXCLUDES: *.jar,cache,logs
      PAUSE_IF_NO_PLAYERS: true
      PLAYERS_ONLINE_CHECK_INTERVAL: 1h
      PRE_BACKUP_SCRIPT: echo "Backup en cours"
      POST_BACKUP_SCRIPT: echo "Backup done"
    volumes:
    - data:/data:ro
    - backups:/backups
    network_mode: "service:server"
    restart: unless-stopped
    
volumes:
  mods: {}
  data: {}
  backups: {}
networks:
    web:
      external: true