#https://github.com/itzg/docker-minecraft-server
#https://github.com/itzg/docker-mc-backup
#https://www.youtube.com/watch?v=PHJE60COs5g&ab_channel=OuiHeberg DNS

services:
  server:
    restart: unless-stopped
    image: itzg/minecraft-server:java17-jdk
    container_name: minecraft-server
    hostname: minecraft-server
    tty: true
    stdin_open: true
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Paris
      ALLOW_FLIGHT: TRUE
      BROADCAST_CONSOLE_TO_OPS: TRUE
      BROADCAST_RCON_TO_OPS: TRUE
      CF_API_KEY: ${CF_API_KEY}
      CF_BASE_DIR: "/data"
      DIFFICULTY: normal
      EULA: TRUE
      ENABLE_STATUS: TRUE
      ENABLE_QUERY: TRUE
      ENABLE_RCON: TRUE
      ENABLE_WHITELIST: TRUE
      FORCE_GAMEMODE: TRUE
      FORGE_VERSION: "47.2.32"
      ICON: /RaBByT-S4.jpg
      MAX_BUILD_HEIGHT: 320 # only under 320
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000000
      MEMORY: "8G"
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator
      MOTD: "§b§l§oRaBByT Season Perso\n§f§kMinecraft docker Server"
      OPS: "RaBByt_Tv,TBMPQF"
      OVERRIDE_ICON: TRUE
      PERSONAL_PORT_MINECRAFT_RCON: ${PERSONAL_PORT_MINECRAFT_RCON}
      PERSONAL_RCON_PWD: ${PERSONAL_RCON_PWD}
      PVP: TRUE
      QUERY_PORT: ${PERSONAL_PORT_MINECRAFT}
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 1
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
      SERVER_NAME: RaBByT_S4
      SIMULATION_DISTANCE: 7
      SNOOPER_ENABLED: FALSE
      SPAWN_PROTECTION: 0
      STOP_DURATION: 180
      TYPE: FORGE
      VERSION: "1.20.1"
      VIEW_DISTANCE: 10
    volumes:
      - /home/docker/mc-perso/:/data
      - /home/docker/mc-s4/RaBByT-S4.jpg:/RaBByT-S4.jpg:ro
      - /home/docker/home-docker/timezone:/etc/timezone:ro
    ports:
      - ${PERSONAL_PORT_MINECRAFT}:25565
    networks:
      - web

networks:
  web:
    name: true