#https://github.com/itzg/docker-minecraft-server & https://docker-minecraft-server.readthedocs.io/en/latest/
#https://github.com/itzg/docker-mc-backup
#https://www.youtube.com/watch?v=PHJE60COs5g&ab_channel=OuiHeberg DNS

services:
  server:
    image: docker.io/itzg/minecraft-server:java17-jdk
    restart: no
    container_name: minecraft-r7-server
    hostname: minecraft-r7-server
    labels:
      diun.enable: true
      diun.watch_repos: true
      gamecontainermanager.enable: true
      gamecontainermanager.group: "Minecraft"
      gamecontainermanager.customlabel0: "r7.${PERSONAL_DOMAINE_NAME}"
    tty: true
    stdin_open: true
    environment:
      TZ: Europe/Paris
      ALLOW_FLIGHT: TRUE
      BROADCAST_CONSOLE_TO_OPS: TRUE
      BROADCAST_RCON_TO_OPS: TRUE
      # CF_API_KEY: ${CF_API_KEY}
      # CF_BASE_DIR: "/data"
      # CF_FILE_ID: 5353015 #Ragnamod-VII-7.1.7
      # CF_SLUG: ragnamod-vii
      DIFFICULTY: normal
      EULA: TRUE
      ENABLE_STATUS: TRUE
      ENABLE_QUERY: TRUE
      ENABLE_RCON: TRUE
      ENABLE_WHITELIST: TRUE
      FORCE_GAMEMODE: TRUE
      FORGEVERSION: "40.2.21"
      ICON: /icon.jpg
      MAX_PLAYERS: 5
      MEMORY: "18G"
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator
      MOTD: |
        §b§l§oRaBByT Season 5:§r§r§r§l§o §r§r§r§2§l§o Ragnamod-VII-7.1.7
        §6§kC'est rigolo cette ligne qui bouge tout le temps
      ONLINE_MODE: TRUE
      OVERRIDE_ICON: TRUE
      PVP: TRUE
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 1
        kill @e[type=item]
      RCON_PASSWORD: ${PERSONAL_RCON_PWD}
      RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
      SIMULATION_DISTANCE: 7
      SNOOPER_ENABLED: FALSE
      SPAWN_PROTECTION: 0
      STOP_DURATION: 180
      TYPE: FORGE
      VERSION: "1.18.2"
      VIEW_DISTANCE: 10
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/minecraft/s5/prod:/data
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/minecraft/RaBByT.jpg:/icon.jpg:ro
    ports:
      - ${PERSONAL_PORT_MINECRAFT}:25565
    networks:
      - games

  # backups: # Not needed to due a backup mod in stack
  #   restart: unless-stopped
  #   image: docker.io/itzg/mc-backup
  #   container_name: minecraft-backups
  #   hostname: minecraft-backups
  #   labels:
  #     diun.enable: true
  #     diun.watch_repos: true
  #     gamecontainermanager.enable: true
  #   environment:
  #     PGID: 1000
  #     PUID: 100
  #     TZ: Europe/Paris
  #     INITIAL_DELAY: 0 # since this service waits for mc to be healthy, no initial delay is needed
  #     BACKUP_INTERVAL: ${PERSONAL_INTERVAL_SAVE}
  #     BACKUP_NAME: RaBByT-S5
  #     PRUNE_BACKUPS_DAYS: 7
  #     PRUNE_RESTIC_RETENTION: --keep-within 7d
  #     RCON_HOST: minecraft-server
  #     RCON_PORT: ${PERSONAL_PORT_MINECRAFT_RCON}
  #     RCON_PASSWORD: ${PERSONAL_RCON_PWD}
  #     PAUSE_IF_NO_PLAYERS: TRUE
  #     DEST_DIR: /backups
  #     SRC_DIR: /data
  #     LINK_LATEST: FALSE
  #     BACKUP_METHOD: tar
  #     TAR_COMPRESS_METHOD: gzip
  #     ZSTD_PARAMETERS: -3 --long=25 --single-thread
  #   volumes:
  #     - /${DOCKER_DATA_DIRECTORY:?data path is required}/repos/home-docker/timezone:/etc/timezone:ro
  #     - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/mc-s5:/data
  #     - /${RAID_DATA_DIRECTORY}/backups/Minecraft/s5:/backups
  #   depends_on:
  #     server:
  #       condition: service_healthy
  #   networks:
  #     - games

networks:
  games:
    name: games