version: "3.8"

services:
  ansible:
    image: rabbyt/ansible_ubuntu
    restart: "no"
    ports:
      - 5985:5985
    environment:
      TZ: Europe/Paris
    volumes:
      - git:/Ansible-perso
      - data:/Ansible-Temp:ro
    command: >
      sh -c "git clone https://github.com/Nicolas-mahe/Ansible-perso.git && \
            cp -r ./Ansible-Temp/ ./Ansible-perso/Ansible/ &&\
            git config --global --add safe.directory /Ansible-perso && \
            cd ./Ansible-perso/Ansible/ && \
            ansible-galaxy collection install -r requirement.yml && \
            ansible-playbook -i inventory.yml playbook.yml"

volumes:
  git: {}
  data: {}
networks:
    web:
      external: true