- name: Zaula-Setup
  hosts: Pc-Zaula
  vars_files: ./vars_zaula.yml
  gather_facts: true
  tasks:
  - name: autorisation chocolatey install
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

- name: Choco Install
  hosts: Pc-Zaula
  vars_files: ./vars_zaula.yml
  gather_facts: true
  tags: loop
  tasks:
  - name: Install Software
    chocolatey.chocolatey.win_chocolatey:
      name: "{{ item }}"
      state: present
    loop: "{{ ChocolateyInstall }}"
    register: software_state
  - name: Reboot Host
    ansible.windows.win_reboot:
    when: software_state.reboot_required