services:
  wireguard:
    restart: unless-stopped
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
      ALLOWEDIPS: 0.0.0.0/0
      INTERFACE: eth0
      INTERNAL_SUBNET: ${PERSONAL_VPN_MASK}
      LOG_CONFS: true
      PEERS: ${PERSONAL_PEER_LIST}
      PEERDNS: ${PERSONAL_DNS}
      PERSISTENTKEEPALIVE_PEERS: all
      SERVERURL: auto
      SERVERPORT: ${PERSONAL_PORT_WIREGUARD}
    ports:
      - ${PERSONAL_PORT_WIREGUARD}:51820/udp
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - /${DOCKER_DATA_DIRECTORY}/docker/docker-data/wireguard:/config
      - /lib/modules:/lib/modules
    networks:
    - vpn

networks:
  vpn:
    name: vpn