version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      SERVERURL: auto
      SERVERPORT: ${PERSONAL_PORT_WIREGUARD}
      PEERS: ${PERSONAL_PEER_LIST}
      PEERDNS: auto
      INTERNAL_SUBNET: ${PERSONAL_VPN_MASK}
      ALLOWEDIPS: 0.0.0.0/0
      LOG_CONFS: true
    ports:
      - ${PERSONAL_PORT_WIREGUARD}:51820/udp
    volumes:
      - /home/docker/wireguard:/config
      - /lib/modules:/lib/modules
    networks:
    - vpn

networks:
  vpn:
    external: true