#docker run -d -p $PERSONAL_AGENT_PORT:9001 --name portainer_agent_beta --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:2.18.4
version: '3'

services:
  portainer_agent:
    image: portainer/agent:2.18.4
    container_name: portainer_agent
    restart: always
    ports:
      - $PERSONAL_AGENT_PORT:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes