version: '3'

services:
  portainer_agent:
    image: portainer/agent:2.18.4
    container_name: portainer_agent
    restart: always
    ports:
      - $PERSONNAL_AGENT_PORT:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    env_file:
      - ../.env
